const notes = [
  {
    name: "Shopping list",
    created: "April 20, 2021",
    category: "Task",
    content: "The some content",
    dates: "",
    archived: false,
  },
  {
    name: "The theory of evolution",
    created: "April 27, 2021",
    category: "Random Thought",
    content: "The some content",
    dates: "",
    archived: true,
  },
  {
    name: "The theory of evolution",
    created: "May 05, 2021",
    category: "Idea",
    content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    dates: "2021-05-03, 2021-05-05",
    archived: false,
  },
  {
    name: "William Gaddis",
    created: "May 07, 2021",
    category: "Quote",
    content: "The some content",
    dates: "",
    archived: false,
  },
  {
    name: "Books",
    created: "May 15, 2021",
    category: "Random Thought",
    content: "The some content",
    dates: "2021-05-03",
    archived: false,
  },
  {
    name: "William Gaddis",
    created: "May 07, 2021",
    category: "Quote",
    content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    dates: "2021-05-03, 2021-05-05, 2022-02-23",
    archived: true,
  },
  {
    name: "New Feature",
    created: "April 27, 2021",
    category: "Random Thought",
    content: "The some content",
    dates: "",
    archived: true,
  },
  {
    name: "Shopping list",
    created: "April 20, 2021",
    category: "Task",
    content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    dates: "",
    archived: false,
  },
];

export default notes;
